[package]
name = "musicus_database"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2", features = ["sqlite"] }
diesel_migrations = "2"
chrono = "0.4"
log = "0.4"
rand = "0.8"
thiserror = "1"
uuid = { version = "1", features = ["v4"] }
