[package]
name = "musicus_import"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13"
glib = "0.16"
gstreamer = "0.19"
gstreamer-pbutils = "0.19"
log = "0.4"
once_cell = "1"
rand = "0.8"
thiserror = "1"
sha2 = "0.10"
tokio = { version = "1", features = ["sync"] }
