//! Diesel declarations for the `*_last_played` database views.
//!
//! These belong to the same migration as the `plays` table, but they cannot
//! live in [`super::schema`]: that file is generated by `diesel print-schema`,
//! which only emits tables, so anything written there would be lost on the next
//! regeneration. They are declared here by hand instead.
//!
//! Each view answers "when was this last played, and how often" for one kind of
//! entity, derived from the play log. `last_played_at` is not nullable in the
//! view itself — a group exists only because at least one play produced it —
//! but a `LEFT JOIN` against an entity that was never played makes it nullable
//! at the query level, which is how these are normally used.

use diesel::{allow_tables_to_appear_in_same_query, joinable, table};

table! {
    recording_last_played (recording_id) {
        recording_id -> Text,
        last_played_at -> Timestamp,
        play_count -> BigInt,
    }
}

table! {
    track_last_played (track_id) {
        track_id -> Text,
        last_played_at -> Timestamp,
        play_count -> BigInt,
    }
}

table! {
    work_last_played (work_id) {
        work_id -> Text,
        last_played_at -> Timestamp,
        play_count -> BigInt,
    }
}

table! {
    person_last_played (person_id) {
        person_id -> Text,
        last_played_at -> Timestamp,
        play_count -> BigInt,
    }
}

// When someone last played *on* a recording, as opposed to
// `person_last_played`, which is about works they composed.
table! {
    performer_last_played (person_id) {
        person_id -> Text,
        last_played_at -> Timestamp,
        play_count -> BigInt,
    }
}

table! {
    instrument_last_played (instrument_id) {
        instrument_id -> Text,
        last_played_at -> Timestamp,
        play_count -> BigInt,
    }
}

table! {
    ensemble_last_played (ensemble_id) {
        ensemble_id -> Text,
        last_played_at -> Timestamp,
        play_count -> BigInt,
    }
}

table! {
    album_last_played (album_id) {
        album_id -> Text,
        last_played_at -> Timestamp,
        play_count -> BigInt,
    }
}

joinable!(recording_last_played -> recordings (recording_id));
joinable!(track_last_played -> tracks (track_id));
joinable!(work_last_played -> works (work_id));
joinable!(person_last_played -> persons (person_id));
joinable!(performer_last_played -> persons (person_id));
joinable!(instrument_last_played -> instruments (instrument_id));
joinable!(ensemble_last_played -> ensembles (ensemble_id));
joinable!(album_last_played -> albums (album_id));

/// Permit one view to appear alongside each of the given tables.
///
/// [`allow_tables_to_appear_in_same_query!`] implements the permission for
/// every *pair* of its arguments, so the tables cannot simply be listed
/// together with the views: that would re-implement the pairs among the base
/// tables that [`super::schema`] already covers, and the duplicate impls do not
/// compile. Expanding one call per (view, table) pair avoids that.
macro_rules! allow_view_with_tables {
    ($view:ident; $($table:ident),+ $(,)?) => {
        $(allow_tables_to_appear_in_same_query!($view, $table);)+
    };
}

/// The search queries join a view against most of the schema at once, so every
/// view is permitted alongside every table rather than only the ones it is
/// derived from.
macro_rules! allow_view_everywhere {
    ($($view:ident),+ $(,)?) => {
        $(allow_view_with_tables!(
            $view;
            album_recordings,
            albums,
            ensemble_persons,
            ensembles,
            instruments,
            meta,
            persons,
            plays,
            recording_ensembles,
            recording_persons,
            recording_tags,
            recordings,
            roles,
            tags,
            track_works,
            tracks,
            work_instruments,
            work_persons,
            work_tags,
            works,
        );)+
    };
}

use super::schema::*;

allow_view_everywhere!(
    recording_last_played,
    track_last_played,
    work_last_played,
    person_last_played,
    performer_last_played,
    instrument_last_played,
    ensemble_last_played,
    album_last_played,
);
