name: Build and Release Flatpak

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
    - uses: actions/checkout@v4

    - name: Build Flatpak
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: de.johrpan.Musicus.flatpak
        manifest-path: flatpak/de.johrpan.Musicus.json
        cache-key: flatpak-builder-${{ github.sha }}

    - name: Upload Flatpak to Release
      uses: softprops/action-gh-release@v2
      with:
        files: de.johrpan.Musicus.flatpak
